# Generated by Django 6.0.7 on 2026-09-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_backfill_availability_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeoff",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="approved",
                max_length=30,
            ),
        ),
    ]
