# Generated by Django 6.0.7 on 2026-09-28 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_actor_type(apps, schema_editor):
    # Rows written before actor_type existed: a recorded user means a user acted.
    AuditLog = apps.get_model("core", "AuditLog")
    AuditLog.objects.filter(user__isnull=False).update(actor_type="user")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("organizations", "0002_membership_capabilities_and_suspension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("system", "System"),
                    ("platform_admin", "Platform admin"),
                    ("api_key", "API key"),
                    ("ai_agent", "AI agent"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="impersonator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impersonated_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["organization", "-created_at"], name="core_auditl_organiz_e98001_idx"
            ),
        ),
        migrations.RunPython(backfill_actor_type, migrations.RunPython.noop),
    ]
