# Generated by Django 6.0.7 on 2026-09-29 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_default_locations"),
        ("organizations", "0002_membership_capabilities_and_suspension"),
        ("services", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="staff_members", to="locations.location"
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="max_daily_appointments",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="online_booking_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="provider_type",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name="StaffServiceOffering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "custom_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offerings",
                        to="locations.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="services.service",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="staff.staffprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("service__name",),
                "indexes": [
                    models.Index(
                        fields=["organization", "service", "is_active"],
                        name="staff_staff_organiz_e1688f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("location__isnull", False)),
                        fields=("staff", "service", "location"),
                        name="offering_unique_per_location",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("location__isnull", True)),
                        fields=("staff", "service"),
                        name="offering_unique_all_locations",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("custom_duration_minutes__isnull", True),
                            ("custom_duration_minutes__gt", 0),
                            _connector="OR",
                        ),
                        name="offering_positive_duration",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("custom_price__isnull", True),
                            ("custom_price__gte", 0),
                            _connector="OR",
                        ),
                        name="offering_price_not_negative",
                    ),
                ],
            },
        ),
    ]
