# Generated by Django 6.0.7 on 2026-10-03 22:34

import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0004_organization_timezone_validator"),
        ("services", "0002_locations_and_policies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("intake", "Intake"),
                            ("consent", "Consent"),
                            ("questionnaire", "Questionnaire"),
                        ],
                        default="intake",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Shown to customers above the form."),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_templates",
                        to="organizations.organization",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(blank=True, related_name="forms", to="services.service"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FormVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="customer_forms.formtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "-number"],
            },
        ),
        migrations.CreateModel(
            name="FormQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Short answer"),
                            ("textarea", "Paragraph"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("yes_no", "Yes or no"),
                            ("select", "One choice"),
                            ("multi_select", "Several choices"),
                            ("signature_placeholder", "Signature (typed name)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=300)),
                ("help_text", models.CharField(blank=True, max_length=500)),
                ("required", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, default=list)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="customer_forms.formversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="formtemplate",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Lower("name"),
                name="form_name_unique_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="formversion",
            constraint=models.UniqueConstraint(
                fields=("template", "number"), name="form_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="formversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("published_at__isnull", True)),
                fields=("template",),
                name="form_one_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="formquestion",
            constraint=models.UniqueConstraint(fields=("version", "key"), name="form_question_key"),
        ),
        migrations.AddConstraint(
            model_name="formquestion",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("version", "position"),
                name="form_question_position",
            ),
        ),
    ]
