# Generated by Django 6.0.7 on 2026-09-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="suspension_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="granted_permissions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="revoked_permissions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("receptionist", "Receptionist"),
                    ("staff", "Staff"),
                    ("customer", "Customer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("receptionist", "Receptionist"),
                    ("staff", "Staff"),
                    ("customer", "Customer"),
                ],
                max_length=20,
            ),
        ),
    ]
