# Generated by Django 6.0.7 on 2026-09-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_membership_capabilities_and_suspension"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="booking_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="brand_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Default (indigo)"),
                    ("blue", "Blue"),
                    ("teal", "Teal"),
                    ("green", "Green"),
                    ("rose", "Rose"),
                    ("violet", "Violet"),
                    ("orange", "Orange"),
                    ("slate", "Slate"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
