# Generated by Django 6.0.7 on 2026-09-29 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_default_locations"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecategory",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="service",
            name="cancellation_policy",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="service",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="locations.location"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="required_provider_type",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="service",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Use a hex color such as #3b82f6."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
