# Generated by Django 6.0.7 on 2026-08-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("specialist", "Specialist"),
                    ("admin", "Admin"),
                    ("owner", "Owner"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
