# Generated by Django 6.0.7 on 2026-09-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_account_status_and_more'),
        ('accounts', '0002_user_role'),
    ]

    operations = [
    ]
