# Generated by Django 6.0.7 on 2026-09-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merge_role_and_email_first"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
