# Generated by Django 6.0.7 on 2026-09-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_email_unique_ignoring_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_platform_staff",
            field=models.BooleanField(default=False),
        ),
    ]
