# Generated by Django 6.0.7 on 2026-08-28 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="slot_duration",
            field=models.PositiveIntegerField(
                default=30, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
