# Generated by Django 6.0.7 on 2026-09-28 18:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_customer_tag_set"),
        ("crm", "0002_backfill_tags_from_json"),
        ("organizations", "0002_membership_capabilities_and_suspension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("customer_created", "Customer created"),
                            ("profile_updated", "Profile updated"),
                            ("consent_changed", "Consent changed"),
                            ("customer_merged", "Duplicate merged"),
                            ("appointment_booked", "Appointment booked"),
                            ("appointment_rescheduled", "Appointment rescheduled"),
                            ("appointment_cancelled", "Appointment cancelled"),
                            ("appointment_completed", "Appointment completed"),
                            ("appointment_no_show", "No-show"),
                            ("note_created", "Note added"),
                            ("tag_added", "Tag added"),
                            ("tag_removed", "Tag removed"),
                            ("email_sent", "Email sent"),
                            ("sms_sent", "SMS sent"),
                            ("form_completed", "Form completed"),
                            ("payment_recorded", "Payment recorded"),
                        ],
                        max_length=40,
                    ),
                ),
                ("subject_type", models.CharField(blank=True, max_length=60)),
                ("subject_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("internal", models.BooleanField(default=False)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="bookings.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["organization", "customer", "-occurred_at"],
                        name="crm_custome_organiz_7028b8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("call", "Phone call"),
                            ("follow_up", "Follow-up"),
                            ("alert", "Alert"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("customer_visible", "Visible to customer"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(max_length=10000)),
                ("pinned", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_notes",
                        to="bookings.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-pinned", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["organization", "customer", "-created_at"],
                        name="crm_custome_organiz_cfc885_idx",
                    )
                ],
            },
        ),
    ]
