# Generated by Django 6.0.7 on 2026-09-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="maximum_locations",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
