# Generated by Django 6.0.7 on 2026-09-29 17:48

import django.db.models.deletion
import locations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_membership_capabilities_and_suspension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("is_default", models.BooleanField(default=False)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=2)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        max_length=64,
                        validators=[locations.models.validate_timezone],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("booking_enabled", models.BooleanField(default=True)),
                ("booking_settings", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_default", "name"),
            },
        ),
        migrations.CreateModel(
            name="LocationClosure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("all_day", models.BooleanField(default=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=120)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closures",
                        to="locations.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("start_date", "start_time"),
            },
        ),
        migrations.CreateModel(
            name="LocationHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours",
                        to="locations.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("weekday", "opens_at"),
            },
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["organization", "is_active"], name="locations_l_organiz_bd40e7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="location_unique_slug_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("organization",),
                name="location_one_default_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_default", False), ("is_active", True), _connector="OR"),
                name="location_default_is_active",
            ),
        ),
        migrations.AddIndex(
            model_name="locationclosure",
            index=models.Index(
                fields=["location", "end_date"], name="locations_l_locatio_cd20ac_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationclosure",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="location_closure_date_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationclosure",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("all_day", True), ("end_time__isnull", True), ("start_time__isnull", True)
                    ),
                    models.Q(
                        ("all_day", False),
                        ("end_time__isnull", False),
                        ("start_time__isnull", False),
                        ("start_time__lt", models.F("end_time")),
                    ),
                    _connector="OR",
                ),
                name="location_closure_times",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationhours",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="location_hours_valid_weekday",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationhours",
            constraint=models.CheckConstraint(
                condition=models.Q(("opens_at__lt", models.F("closes_at"))),
                name="location_hours_open_before_close",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationhours",
            constraint=models.UniqueConstraint(
                fields=("location", "weekday", "opens_at"), name="location_hours_unique_start"
            ),
        ),
    ]
