# Generated by Django 6.0.7 on 2026-09-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_customer_constraints"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="tag_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="customers",
                through="crm.CustomerTag",
                through_fields=("customer", "tag"),
                to="crm.tag",
            ),
        ),
    ]
