# M2.4: digits-only phone copy for format-independent search.
# Generated by Django 6.0.7 on 2026-09-28 19:28

from django.db import migrations, models


def fill_phone_search(apps, schema_editor):
    Customer = apps.get_model("bookings", "Customer")

    def digits(value):
        return "".join(ch for ch in value or "" if ch.isdigit())

    for customer in Customer.objects.iterator():
        customer.phone_search = " ".join(
            filter(None, (digits(customer.phone), digits(customer.secondary_phone)))
        )
        customer.save(update_fields=["phone_search"])


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_customer_tag_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_search",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.RunPython(fill_phone_search, migrations.RunPython.noop),
    ]
