# Generated by Django 6.0.7 on 2026-09-29 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_customer_trigram_indexes"),
        ("locations", "0002_default_locations"),
        ("organizations", "0002_membership_capabilities_and_suspension"),
        ("services", "0002_locations_and_policies"),
        ("staff", "0003_backfill_locations_and_offerings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="buffer_after_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="buffer_before_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="booking",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("public_booking", "Online booking page"),
                    ("customer_portal", "Customer portal"),
                    ("reception", "Reception"),
                    ("staff", "Staff"),
                    ("api", "API"),
                    ("ai_agent", "AI agent"),
                    ("import", "Import"),
                    ("admin", "Admin"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["organization", "location", "start_datetime"],
                name="bookings_bo_organiz_d7153e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("organization", "idempotency_key"),
                name="booking_unique_idempotency_key_per_org",
            ),
        ),
    ]
