# Generated by Django 6.0.7 on 2026-09-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_booking_no_overlap_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingstatushistory",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="booking",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingstatushistory",
            name="reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="bookingstatushistory",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public_booking", "Online booking page"),
                    ("customer_portal", "Customer portal"),
                    ("reception", "Reception"),
                    ("staff", "Staff"),
                    ("api", "API"),
                    ("ai_agent", "AI agent"),
                    ("import", "Import"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
