# Generated by Django 6.0.7 on 2026-09-30 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_status_history_reason_source"),
        ("locations", "0002_default_locations"),
        ("organizations", "0003_booking_page_branding"),
        ("services", "0002_locations_and_policies"),
        ("staff", "0003_backfill_locations_and_offerings"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waitlist_entries",
                to="bookings.customer",
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="waitlist_entries",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public_booking", "Online booking page"),
                    ("customer_portal", "Customer portal"),
                    ("reception", "Reception"),
                    ("staff", "Staff"),
                    ("api", "API"),
                    ("ai_agent", "AI agent"),
                    ("import", "Import"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="time_of_day",
            field=models.CharField(
                choices=[
                    ("any", "Any time"),
                    ("morning", "Morning (before 12:00)"),
                    ("afternoon", "Afternoon (12:00-17:00)"),
                    ("evening", "Evening (after 17:00)"),
                ],
                default="any",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="waitlistentry",
            index=models.Index(
                fields=["organization", "service", "status"], name="bookings_wa_organiz_9a60c3_idx"
            ),
        ),
    ]
