# Generated by Django 6.0.7 on 2026-09-30 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0012_waitlist_enhancement"),
        ("notifications", "0002_notification_sending_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="related_waitlist_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_logs",
                to="bookings.waitlistentry",
            ),
        ),
    ]
