# Generated by Django 6.0.7 on 2026-10-03 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_forms", "0002_form_assignments"),
        ("notifications", "0003_waitlist_enhancement"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="related_form_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_logs",
                to="customer_forms.formassignment",
            ),
        ),
    ]
